// Added by RBW

public class HarvestTimeEntry {  

  public String   id              { get; set; }
  public String   notes           { get; set; }
  public String   spentat         { get; set; }
  public Decimal  hours           { get; set; }
  public String   userid          { get; set; }
  public String   projectid       { get; set; }
  public String   taskid          { get; set; }  
  public String   createdat       { get; set; }
  public String   updatedat       { get; set; }
  public Boolean  isadjustment    { get; set; }
  public Boolean  isclosed        { get; set; }
    
}